### ISSUE TITLE
email invalid

### ISSUE THREAD

**Issue by kishore2036** [CheckPointSW/reputation-service-api#13]
This issue is created regarding an email address mentioned in reputation service API 

I tried sending an email to TCAPI_SUPPORT@checkpoint.com <TCAPI_SUPPORT@checkpoint.com> for API key and received bounce back stating it is invalid.

**Comment by chkp-aviadl** [comment]
Hi @kishore2036 ,

I tested the mailing list again today and it is working.  
please contact me if the issue still happening - aviadl@checkpoint.com

**Comment by chkp-aviadl** [comment]
Thanks for the report.  
This issue is now resolved

**Comment by kishore2036** [comment]
Thanks
